_hpack-common:  !include ../../hpack-common.yaml
<<:             *toplevel

name:           gugugu-lang-scala

dependencies:
  - base >= 4.12 && < 5

library:
  source-dirs: src

  dependencies:
    - gugugu-core
    - gugugu-utils

    - bytestring
    - containers
    - directory
    - filepath
    - mtl
    - text

    - optparse-applicative

    - file-embed

executables:
  gugugu-scala:
    main:                gugugu-scala.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gugugu-lang-scala
