[package]
name = "gugugu-rust-example"
version = "0.0.0"
edition = "2018"

[dependencies]
chrono = "0.4"
time = "0.1"
serde_json = "1.0"
http = "0.2"
hyper = "0.13"
tokio = { version = "0.2", features = ["io-std"] }
