jsonhttp:
  scala:
    server:
      command: gradle runJsonHttpServer
      cwd: examples/lang/scala
    client:
      command: gradle runJsonHttpClient
      cwd: examples/lang/scala
  typescript:
    server:
      command: node build/js/src/jsonhttp/server.js
      cwd: examples/lang/typescript
