jsonhttp:
  haskell:
    server:
      command: stack exec -- gugugu-example-haskell-jsonhttp-server
      cwd: examples/lang/haskell
    client:
      command: stack exec -- gugugu-example-haskell-jsonhttp-client
      cwd: examples/lang/haskell
  python:
    server:
      command: python -m guguguexamples.jsonhttp.server
      cwd: examples/lang/python
    client:
      command: python -m guguguexamples.jsonhttp.client
      cwd: examples/lang/python
  rust:
    server:
      command: cargo run --bin gugugu-example-rust-jsonhttp-server
      cwd: examples/lang/rust
  scala:
    server:
      command: gradle runJsonHttpServer
      cwd: examples/lang/scala
    client:
      command: gradle runJsonHttpClient
      cwd: examples/lang/scala
  typescript:
    server:
      command: node build/js/src/jsonhttp/server.js
      cwd: examples/lang/typescript
    client:
      command: node build/js/src/jsonhttp/client.js
      cwd: examples/lang/typescript
