name:                gugugu-haskell-example

dependencies:
  - base >= 4.7 && < 5
  - text
  - vector

  - time

  - mtl
  - aeson
  - scientific
  - unordered-containers

library:
  source-dirs:
    - src
    - build/generated/gugugu
