name:                gugugu-haskell-example

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text
  - vector

  - time

  - mtl
  - aeson
  - scientific
  - unordered-containers

  - case-insensitive
  - http-types


library:
  source-dirs:
    - src
    - build/generated/gugugu

executables:
  gugugu-example-haskell-jsonhttp-server:
    main:                jsonhttp-server.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gugugu-haskell-example
      - bytestring
      - wai
      - warp
  gugugu-example-haskell-jsonhttp-client:
    main:                jsonhttp-client.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gugugu-haskell-example
      - http-client
