name: Build
on:
  push:
    branches:
      - master
      - feature/*
      - ci/*
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-2022
          - macos-12
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: "8.8.4"
          enable-stack: true
      - run: bash .github/workflows/setup.sh
        id: setup
        shell: bash
      - uses: actions/cache@v3
        with:
          key: stack-all-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('stack.yaml', '**/package.yaml', 'hpack-common.yaml') }}
          path: ${{ steps.setup.STACK_ROOT }}
      - run: stack --system-ghc build --pedantic
        shell: bash
